# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wine',
            new_name='Landlord',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='wine',
            new_name='landlord',
        ),
        migrations.AddField(
            model_name='review',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='apt_condition',
            field=models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='communication',
            field=models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='maintenance_eff',
            field=models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rent_again',
            field=models.CharField(choices=[(b'Yes', b'Yes'), (b'No', b'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')]),
        ),
    ]
