# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171006_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(verbose_name=b'date published'),
        ),
    ]
